# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-19 16:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_events'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='EventType',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
